### ISSUE TITLE
Please add support for AliCloud

### ISSUE THREAD

**Issue by zelenkovsky** [NVIDIA-Omniverse/IsaacSim-Automator#1]
[AliCloud](https://us.alibabacloud.com/en) is very popular in mainland China. How can we deploy [IsaacSim ](https://developer.nvidia.com/isaac-sim)directly into [Elastic GPU Service](https://www.alibabacloud.com/product/heterogeneous_computing).

**Comment by myurasov** [comment]
Thanks, @zelenkovsky, we are looking into that. :)
